'use client';

import { useState } from 'react';

export default function LegalDisclaimer() {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="mt-6 rounded-lg border border-brand-border bg-brand-dark/60 text-xs text-slate-500">
      <button
        type="button"
        onClick={() => setExpanded(p => !p)}
        className="w-full flex items-center justify-between px-4 py-3 text-left hover:text-slate-400 transition-colors"
      >
        <span>
          🔒 <span className="font-semibold">Terms of Use & Legal Disclaimer</span>
          {' '}— By running an audit you agree to these terms.
        </span>
        <span className="ml-2 flex-shrink-0">{expanded ? '▲' : '▼'}</span>
      </button>

      {expanded && (
        <div className="px-4 pb-4 space-y-3 border-t border-brand-border pt-3 leading-relaxed">

          <p className="font-semibold text-slate-400">1. Informational Purpose Only</p>
          <p>
            PresenceIQ is an AI-powered research tool that surfaces publicly available information from across the internet. Results are generated by AI-assisted web search and may be incomplete, inaccurate, or out of date. We do not guarantee the accuracy, completeness, or timeliness of any information returned.
          </p>

          <p className="font-semibold text-slate-400">2. Not a Consumer Reporting Agency (FCRA Notice)</p>
          <p>
            PresenceIQ is <strong className="text-slate-300">NOT</strong> a Consumer Reporting Agency as defined by the Fair Credit Reporting Act (FCRA), 15 U.S.C. § 1681 et seq. The information provided is <strong className="text-slate-300">NOT</strong> a &ldquo;consumer report.&rdquo; You may <strong className="text-slate-300">NOT</strong> use results from this tool for: employment screening, tenant screening, credit or insurance eligibility decisions, or any other purpose regulated by the FCRA. Using consumer report data in violation of FCRA may result in civil and criminal liability.
          </p>

          <p className="font-semibold text-slate-400">3. Intended Use</p>
          <p>
            This tool is intended for: (a) professionals auditing their own digital presence for reputation management purposes; (b) businesses conducting legitimate competitive research; and (c) marketing professionals assessing brand visibility. Any other use is prohibited.
          </p>

          <p className="font-semibold text-slate-400">4. Prohibited Uses</p>
          <p>
            You agree NOT to use this tool or its results to: (a) harass, stalk, intimidate, or harm any individual; (b) engage in unauthorized data collection or scraping; (c) make employment, housing, or credit decisions about individuals; (d) violate any federal, state, or local law; (e) collect information about minors; or (f) impersonate another person or entity. Violation of these terms may expose you to civil and criminal liability under applicable law, including but not limited to the Computer Fraud and Abuse Act (CFAA), 18 U.S.C. § 1030, and applicable state privacy statutes.
          </p>

          <p className="font-semibold text-slate-400">5. Accuracy Disclaimer</p>
          <p>
            Digital presence data is derived from AI-powered web search and may reflect information that is outdated, incomplete, or attributed to the wrong individual — especially for common names. Results should be independently verified before being relied upon for any business decision. PresenceIQ, its operators, and affiliates are not liable for any inaccuracies in the results.
          </p>

          <p className="font-semibold text-slate-400">6. No Legal, Financial, or Professional Advice</p>
          <p>
            Nothing on this platform constitutes legal, financial, medical, or other professional advice. Recommendations provided are general in nature and should not be acted upon without consulting a qualified professional.
          </p>

          <p className="font-semibold text-slate-400">7. Privacy</p>
          <p>
            Information you submit to this tool (name, business name, profile URLs) is used solely to generate your audit. We do not sell your personal information to third parties. Email addresses collected via our community sign-up are used only for the stated purpose of delivering reports and newsletters. See our full Privacy Policy for details.
          </p>

          <p className="font-semibold text-slate-400">8. Limitation of Liability</p>
          <p>
            To the maximum extent permitted by law, PresenceIQ and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of this tool or reliance on its results, even if advised of the possibility of such damages.
          </p>

          <p className="text-slate-600 mt-2">
            By clicking &ldquo;Run My Free Audit,&rdquo; you confirm that you have read, understood, and agree to these terms, and that you are at least 18 years of age.
          </p>
        </div>
      )}
    </div>
  );
}
